#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
#  urls:
#    - "http://127.0.0.1:8080/"
#    - "http://0.0.0.0:8080/"
#    - "http://192.168.0.182:8080/"
discussions:
  repository:
    test: "$DB_TYPE_TEST:inmemory"
    prod: "$DB_TYPE_PROD:psql"
    psql:
      password: postgres-pass
      schema: discussions
      url: jdbc:postgresql://localhost:5432/discussions
      user: postgres

jwt:
  secret: "secret"
  issuer: "MusicBroker"
  audience: "music-users"
  realm: "music-discussions"
  clientId: "music-broker-service"

#jwt:
#  issuer: "http://localhost:8081/auth/realms/music-broker"
#  audience: "music-users"
#  realm: "music-discussions"
#  clientId: "music-broker-service"
#  certUrl: "http://localhost:8081/auth/realms/music-broker/protocol/openid-connect/certs"
