openapi: 3.0.4
info:
  title: Music broker log models
  description: Log models for logging services of music broker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        discussion:
          $ref: '#/components/schemas/DiscussionLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    DiscussionLogModel:
      title: Модель лога для микросервиса Music broker
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - close
            - allDiscussions
            - usersDiscussions
        requestDiscussion:
          $ref: '#/components/schemas/DiscussionLog'
        responseDiscussion:
          $ref: '#/components/schemas/DiscussionLog'
        responseDiscussions:
          type: array
          items:
            $ref: '#/components/schemas/DiscussionLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    DiscussionLog:
      title: Модель лога для обсуждения
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        soundUrl:
          type: string
        answers:
          type: array
          items:
            type: string
        status:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string